/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type LevelId = bigint;
export type MistakeTag = { 'TimeIssue' : null } |
  { 'SillyMistake' : null } |
  { 'AlgebraMistake' : null } |
  { 'ConceptError' : null } |
  { 'Guessed' : null };
export type QuestionNumber = bigint;
export interface QuestionRecord {
  'status' : QuestionStatus,
  'templateId' : TemplateId,
  'lastAttemptedAt' : [] | [Timestamp],
  'mistakeTags' : Array<MistakeTag>,
  'difficultyRating' : [] | [bigint],
  'markedForRedo' : boolean,
  'notes' : [] | [string],
  'questionNumber' : QuestionNumber,
}
export type QuestionStatus = { 'Incorrect' : null } |
  { 'Correct' : null } |
  { 'Unattempted' : null } |
  { 'Revisit' : null };
export interface QuestionTemplate {
  'id' : TemplateId,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type Result = { 'ok' : QuestionTemplate } |
  { 'err' : string };
export type Result_1 = { 'ok' : TemplateLevel } |
  { 'err' : string };
export type Result_2 = { 'ok' : null } |
  { 'err' : string };
export type TemplateId = bigint;
export interface TemplateLevel {
  'id' : LevelId,
  'startQuestion' : QuestionNumber,
  'order' : bigint,
  'templateId' : TemplateId,
  'name' : string,
  'endQuestion' : QuestionNumber,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addLevel' : ActorMethod<
    [TemplateId, string, bigint, bigint, bigint],
    Result_1
  >,
  'createTemplate' : ActorMethod<[string], QuestionTemplate>,
  'deleteLevel' : ActorMethod<[LevelId], Result_2>,
  'deleteTemplate' : ActorMethod<[TemplateId], Result_2>,
  'getQuestionRecord' : ActorMethod<
    [TemplateId, bigint],
    [] | [QuestionRecord]
  >,
  'getRedoMarkedQuestions' : ActorMethod<[TemplateId], Array<QuestionRecord>>,
  'getTemplateLevels' : ActorMethod<[TemplateId], Array<TemplateLevel>>,
  'getTemplateRecords' : ActorMethod<[TemplateId], Array<QuestionRecord>>,
  'getTemplates' : ActorMethod<[], Array<QuestionTemplate>>,
  'setQuestionStatus' : ActorMethod<
    [TemplateId, bigint, QuestionStatus],
    QuestionRecord
  >,
  'updateLevel' : ActorMethod<[LevelId, string, bigint, bigint], Result_1>,
  'updateQuestionDetail' : ActorMethod<
    [
      TemplateId,
      bigint,
      [] | [string],
      Array<MistakeTag>,
      [] | [bigint],
      boolean,
      [] | [Timestamp],
    ],
    QuestionRecord
  >,
  'updateTemplate' : ActorMethod<[TemplateId, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];