/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TemplateId = IDL.Nat;
export const LevelId = IDL.Nat;
export const QuestionNumber = IDL.Nat;
export const TemplateLevel = IDL.Record({
  'id' : LevelId,
  'startQuestion' : QuestionNumber,
  'order' : IDL.Nat,
  'templateId' : TemplateId,
  'name' : IDL.Text,
  'endQuestion' : QuestionNumber,
});
export const Result_1 = IDL.Variant({ 'ok' : TemplateLevel, 'err' : IDL.Text });
export const Timestamp = IDL.Int;
export const QuestionTemplate = IDL.Record({
  'id' : TemplateId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const QuestionStatus = IDL.Variant({
  'Incorrect' : IDL.Null,
  'Correct' : IDL.Null,
  'Unattempted' : IDL.Null,
  'Revisit' : IDL.Null,
});
export const MistakeTag = IDL.Variant({
  'TimeIssue' : IDL.Null,
  'SillyMistake' : IDL.Null,
  'AlgebraMistake' : IDL.Null,
  'ConceptError' : IDL.Null,
  'Guessed' : IDL.Null,
});
export const QuestionRecord = IDL.Record({
  'status' : QuestionStatus,
  'templateId' : TemplateId,
  'lastAttemptedAt' : IDL.Opt(Timestamp),
  'mistakeTags' : IDL.Vec(MistakeTag),
  'difficultyRating' : IDL.Opt(IDL.Nat),
  'markedForRedo' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
  'questionNumber' : QuestionNumber,
});
export const Result = IDL.Variant({
  'ok' : QuestionTemplate,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'addLevel' : IDL.Func(
      [TemplateId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [Result_1],
      [],
    ),
  'createTemplate' : IDL.Func([IDL.Text], [QuestionTemplate], []),
  'deleteLevel' : IDL.Func([LevelId], [Result_2], []),
  'deleteTemplate' : IDL.Func([TemplateId], [Result_2], []),
  'getQuestionRecord' : IDL.Func(
      [TemplateId, IDL.Nat],
      [IDL.Opt(QuestionRecord)],
      ['query'],
    ),
  'getRedoMarkedQuestions' : IDL.Func(
      [TemplateId],
      [IDL.Vec(QuestionRecord)],
      ['query'],
    ),
  'getTemplateLevels' : IDL.Func(
      [TemplateId],
      [IDL.Vec(TemplateLevel)],
      ['query'],
    ),
  'getTemplateRecords' : IDL.Func(
      [TemplateId],
      [IDL.Vec(QuestionRecord)],
      ['query'],
    ),
  'getTemplates' : IDL.Func([], [IDL.Vec(QuestionTemplate)], ['query']),
  'setQuestionStatus' : IDL.Func(
      [TemplateId, IDL.Nat, QuestionStatus],
      [QuestionRecord],
      [],
    ),
  'updateLevel' : IDL.Func(
      [LevelId, IDL.Text, IDL.Nat, IDL.Nat],
      [Result_1],
      [],
    ),
  'updateQuestionDetail' : IDL.Func(
      [
        TemplateId,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Vec(MistakeTag),
        IDL.Opt(IDL.Nat),
        IDL.Bool,
        IDL.Opt(Timestamp),
      ],
      [QuestionRecord],
      [],
    ),
  'updateTemplate' : IDL.Func([TemplateId, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TemplateId = IDL.Nat;
  const LevelId = IDL.Nat;
  const QuestionNumber = IDL.Nat;
  const TemplateLevel = IDL.Record({
    'id' : LevelId,
    'startQuestion' : QuestionNumber,
    'order' : IDL.Nat,
    'templateId' : TemplateId,
    'name' : IDL.Text,
    'endQuestion' : QuestionNumber,
  });
  const Result_1 = IDL.Variant({ 'ok' : TemplateLevel, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const QuestionTemplate = IDL.Record({
    'id' : TemplateId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const QuestionStatus = IDL.Variant({
    'Incorrect' : IDL.Null,
    'Correct' : IDL.Null,
    'Unattempted' : IDL.Null,
    'Revisit' : IDL.Null,
  });
  const MistakeTag = IDL.Variant({
    'TimeIssue' : IDL.Null,
    'SillyMistake' : IDL.Null,
    'AlgebraMistake' : IDL.Null,
    'ConceptError' : IDL.Null,
    'Guessed' : IDL.Null,
  });
  const QuestionRecord = IDL.Record({
    'status' : QuestionStatus,
    'templateId' : TemplateId,
    'lastAttemptedAt' : IDL.Opt(Timestamp),
    'mistakeTags' : IDL.Vec(MistakeTag),
    'difficultyRating' : IDL.Opt(IDL.Nat),
    'markedForRedo' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
    'questionNumber' : QuestionNumber,
  });
  const Result = IDL.Variant({ 'ok' : QuestionTemplate, 'err' : IDL.Text });
  
  return IDL.Service({
    'addLevel' : IDL.Func(
        [TemplateId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [Result_1],
        [],
      ),
    'createTemplate' : IDL.Func([IDL.Text], [QuestionTemplate], []),
    'deleteLevel' : IDL.Func([LevelId], [Result_2], []),
    'deleteTemplate' : IDL.Func([TemplateId], [Result_2], []),
    'getQuestionRecord' : IDL.Func(
        [TemplateId, IDL.Nat],
        [IDL.Opt(QuestionRecord)],
        ['query'],
      ),
    'getRedoMarkedQuestions' : IDL.Func(
        [TemplateId],
        [IDL.Vec(QuestionRecord)],
        ['query'],
      ),
    'getTemplateLevels' : IDL.Func(
        [TemplateId],
        [IDL.Vec(TemplateLevel)],
        ['query'],
      ),
    'getTemplateRecords' : IDL.Func(
        [TemplateId],
        [IDL.Vec(QuestionRecord)],
        ['query'],
      ),
    'getTemplates' : IDL.Func([], [IDL.Vec(QuestionTemplate)], ['query']),
    'setQuestionStatus' : IDL.Func(
        [TemplateId, IDL.Nat, QuestionStatus],
        [QuestionRecord],
        [],
      ),
    'updateLevel' : IDL.Func(
        [LevelId, IDL.Text, IDL.Nat, IDL.Nat],
        [Result_1],
        [],
      ),
    'updateQuestionDetail' : IDL.Func(
        [
          TemplateId,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Vec(MistakeTag),
          IDL.Opt(IDL.Nat),
          IDL.Bool,
          IDL.Opt(Timestamp),
        ],
        [QuestionRecord],
        [],
      ),
    'updateTemplate' : IDL.Func([TemplateId, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };