/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result = {
    __kind__: "ok";
    ok: QuestionTemplate;
} | {
    __kind__: "err";
    err: string;
};
export interface QuestionRecord {
    status: QuestionStatus;
    templateId: TemplateId;
    lastAttemptedAt?: Timestamp;
    mistakeTags: Array<MistakeTag>;
    difficultyRating?: bigint;
    markedForRedo: boolean;
    notes?: string;
    questionNumber: QuestionNumber;
}
export type TemplateId = bigint;
export type QuestionNumber = bigint;
export type LevelId = bigint;
export interface QuestionTemplate {
    id: TemplateId;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export type Result_1 = {
    __kind__: "ok";
    ok: TemplateLevel;
} | {
    __kind__: "err";
    err: string;
};
export interface TemplateLevel {
    id: LevelId;
    startQuestion: QuestionNumber;
    order: bigint;
    templateId: TemplateId;
    name: string;
    endQuestion: QuestionNumber;
}
export enum MistakeTag {
    TimeIssue = "TimeIssue",
    SillyMistake = "SillyMistake",
    AlgebraMistake = "AlgebraMistake",
    ConceptError = "ConceptError",
    Guessed = "Guessed"
}
export enum QuestionStatus {
    Incorrect = "Incorrect",
    Correct = "Correct",
    Unattempted = "Unattempted",
    Revisit = "Revisit"
}
export interface backendInterface {
    addLevel(templateId: TemplateId, name: string, startQuestion: bigint, endQuestion: bigint, order: bigint): Promise<Result_1>;
    createTemplate(name: string): Promise<QuestionTemplate>;
    deleteLevel(id: LevelId): Promise<Result_2>;
    deleteTemplate(id: TemplateId): Promise<Result_2>;
    getQuestionRecord(templateId: TemplateId, questionNumber: bigint): Promise<QuestionRecord | null>;
    getRedoMarkedQuestions(templateId: TemplateId): Promise<Array<QuestionRecord>>;
    getTemplateLevels(templateId: TemplateId): Promise<Array<TemplateLevel>>;
    getTemplateRecords(templateId: TemplateId): Promise<Array<QuestionRecord>>;
    getTemplates(): Promise<Array<QuestionTemplate>>;
    setQuestionStatus(templateId: TemplateId, questionNumber: bigint, status: QuestionStatus): Promise<QuestionRecord>;
    updateLevel(id: LevelId, name: string, startQuestion: bigint, endQuestion: bigint): Promise<Result_1>;
    updateQuestionDetail(templateId: TemplateId, questionNumber: bigint, notes: string | null, mistakeTags: Array<MistakeTag>, difficultyRating: bigint | null, markedForRedo: boolean, lastAttemptedAt: Timestamp | null): Promise<QuestionRecord>;
    updateTemplate(id: TemplateId, name: string): Promise<Result>;
}
import type { MistakeTag as _MistakeTag, QuestionNumber as _QuestionNumber, QuestionRecord as _QuestionRecord, QuestionStatus as _QuestionStatus, QuestionTemplate as _QuestionTemplate, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, TemplateId as _TemplateId, TemplateLevel as _TemplateLevel, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addLevel(arg0: TemplateId, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addLevel(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLevel(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTemplate(arg0: string): Promise<QuestionTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.createTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTemplate(arg0);
            return result;
        }
    }
    async deleteLevel(arg0: LevelId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLevel(arg0);
                return from_candid_Result_2_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLevel(arg0);
            return from_candid_Result_2_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTemplate(arg0: TemplateId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemplate(arg0);
                return from_candid_Result_2_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemplate(arg0);
            return from_candid_Result_2_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionRecord(arg0: TemplateId, arg1: bigint): Promise<QuestionRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionRecord(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionRecord(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRedoMarkedQuestions(arg0: TemplateId): Promise<Array<QuestionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRedoMarkedQuestions(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRedoMarkedQuestions(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplateLevels(arg0: TemplateId): Promise<Array<TemplateLevel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplateLevels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplateLevels(arg0);
            return result;
        }
    }
    async getTemplateRecords(arg0: TemplateId): Promise<Array<QuestionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplateRecords(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplateRecords(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplates(): Promise<Array<QuestionTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplates();
            return result;
        }
    }
    async setQuestionStatus(arg0: TemplateId, arg1: bigint, arg2: QuestionStatus): Promise<QuestionRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.setQuestionStatus(arg0, arg1, to_candid_QuestionStatus_n17(this._uploadFile, this._downloadFile, arg2));
                return from_candid_QuestionRecord_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setQuestionStatus(arg0, arg1, to_candid_QuestionStatus_n17(this._uploadFile, this._downloadFile, arg2));
            return from_candid_QuestionRecord_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLevel(arg0: LevelId, arg1: string, arg2: bigint, arg3: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLevel(arg0, arg1, arg2, arg3);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLevel(arg0, arg1, arg2, arg3);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateQuestionDetail(arg0: TemplateId, arg1: bigint, arg2: string | null, arg3: Array<MistakeTag>, arg4: bigint | null, arg5: boolean, arg6: Timestamp | null): Promise<QuestionRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestionDetail(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n20(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg6));
                return from_candid_QuestionRecord_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestionDetail(arg0, arg1, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n20(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg6));
            return from_candid_QuestionRecord_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTemplate(arg0: TemplateId, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTemplate(arg0, arg1);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTemplate(arg0, arg1);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_MistakeTag_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MistakeTag): MistakeTag {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionRecord_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionRecord): QuestionRecord {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionStatus): QuestionStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuestionRecord]): QuestionRecord | null {
    return value.length === 0 ? null : from_candid_QuestionRecord_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _QuestionStatus;
    templateId: _TemplateId;
    lastAttemptedAt: [] | [_Timestamp];
    mistakeTags: Array<_MistakeTag>;
    difficultyRating: [] | [bigint];
    markedForRedo: boolean;
    notes: [] | [string];
    questionNumber: _QuestionNumber;
}): {
    status: QuestionStatus;
    templateId: TemplateId;
    lastAttemptedAt?: Timestamp;
    mistakeTags: Array<MistakeTag>;
    difficultyRating?: bigint;
    markedForRedo: boolean;
    notes?: string;
    questionNumber: QuestionNumber;
} {
    return {
        status: from_candid_QuestionStatus_n8(_uploadFile, _downloadFile, value.status),
        templateId: value.templateId,
        lastAttemptedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.lastAttemptedAt)),
        mistakeTags: from_candid_vec_n11(_uploadFile, _downloadFile, value.mistakeTags),
        difficultyRating: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.difficultyRating)),
        markedForRedo: value.markedForRedo,
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        questionNumber: value.questionNumber
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    TimeIssue: null;
} | {
    SillyMistake: null;
} | {
    AlgebraMistake: null;
} | {
    ConceptError: null;
} | {
    Guessed: null;
}): MistakeTag {
    return "TimeIssue" in value ? MistakeTag.TimeIssue : "SillyMistake" in value ? MistakeTag.SillyMistake : "AlgebraMistake" in value ? MistakeTag.AlgebraMistake : "ConceptError" in value ? MistakeTag.ConceptError : "Guessed" in value ? MistakeTag.Guessed : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TemplateLevel;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TemplateLevel;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _QuestionTemplate;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: QuestionTemplate;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Incorrect: null;
} | {
    Correct: null;
} | {
    Unattempted: null;
} | {
    Revisit: null;
}): QuestionStatus {
    return "Incorrect" in value ? QuestionStatus.Incorrect : "Correct" in value ? QuestionStatus.Correct : "Unattempted" in value ? QuestionStatus.Unattempted : "Revisit" in value ? QuestionStatus.Revisit : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MistakeTag>): Array<MistakeTag> {
    return value.map((x)=>from_candid_MistakeTag_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestionRecord>): Array<QuestionRecord> {
    return value.map((x)=>from_candid_QuestionRecord_n6(_uploadFile, _downloadFile, x));
}
function to_candid_MistakeTag_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MistakeTag): _MistakeTag {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionStatus): _QuestionStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionStatus): {
    Incorrect: null;
} | {
    Correct: null;
} | {
    Unattempted: null;
} | {
    Revisit: null;
} {
    return value == QuestionStatus.Incorrect ? {
        Incorrect: null
    } : value == QuestionStatus.Correct ? {
        Correct: null
    } : value == QuestionStatus.Unattempted ? {
        Unattempted: null
    } : value == QuestionStatus.Revisit ? {
        Revisit: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MistakeTag): {
    TimeIssue: null;
} | {
    SillyMistake: null;
} | {
    AlgebraMistake: null;
} | {
    ConceptError: null;
} | {
    Guessed: null;
} {
    return value == MistakeTag.TimeIssue ? {
        TimeIssue: null
    } : value == MistakeTag.SillyMistake ? {
        SillyMistake: null
    } : value == MistakeTag.AlgebraMistake ? {
        AlgebraMistake: null
    } : value == MistakeTag.ConceptError ? {
        ConceptError: null
    } : value == MistakeTag.Guessed ? {
        Guessed: null
    } : value;
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MistakeTag>): Array<_MistakeTag> {
    return value.map((x)=>to_candid_MistakeTag_n21(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
